language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "Qgk1D83PTbg1KfGT7GfHQ0gAMwsJTRmgeCvTdwW6rRFMdAr6gJh5YoHSmUHerONwxWVKaR5xQOEz9Ujs8mEXqnzxAMnK5BEedngFb16kMsBj6jpJtSZIgs5vTqnRrS+C1e/6k4uByUS+cnPCXngh6Rkmi1BSAsVFezRGHSZGWsDYgdN5iV5SS3rW1HEFqQ9V9N1hXXYLVqz8myN/HlCyDwsTmYyyHtWFT6QNH5ctooXQbNeZUjxjdk0GytRmehFYRjxJ+DXERbBO1rWGnrLzv+7ja5DsgnMgFO+3OnSWcTpGPTf5xGji01L46uLoxeCGnZ6210epBDljSIjC89g6VOJfju06Ml+qpsFjp5xMq3XYpwlY2igdCg8YwKBgrDU50u63733cZeQTorUzhf9T4TOftHY3Ih/earVKivqqw2eHBwDsT4s4QcwnnMWVro51cIvHoTZf0A9V/G415cgZ6Rhjtk7yfT3ZQsS59X5Zeki9kXRFZclsxBg8bGGX5wUd6HRjT86qgaK/OCMCWiJqJ2Wd1ANURGCdwhpto6YJQAXtEtcCzB2ltCdnVCMzQhCUR0R0UBZaIVRNGFwRonvxLJZYbiz/zu16urJ6z9FIpwe0jEDI45FrcdL1ShoGc/CTra5DuyBVzJpj6wHt6HdU86kvGcYgS+eQfWJXXLmb/ZE="
